#pragma once

// Default Widget Colors

#define DEFCOLOR_NORMAL					0xFFFFB023
#define DEFCOLOR_LIGHT					0xFFF0CB63
#define DEFCOLOR_DARK					0xFFC8960C
#define DEFCOLOR_DISABLE				0xFF808080
#define DEFCOLOR_BACKGROUND				0x77000000

//#define DEFCOLOR_TEXT					0xFFFFFF
#define DEFCOLOR_PEN_HIGHLIGHT			0xFFFFFFFF

// Frame Default
#define DEFCOLOR_FRAME_PLANE			DEFCOLOR_BACKGROUND
#define DEFCOLOR_FRAME_OUTLINE			DEFCOLOR_NORMAL
#define DEFCOLOR_FRAME_TEXT				0xFFFFFFFF

// Label
//#define DEFCOLOR_MLABEL_TEXT			DEFCOLOR_NORMAL
#define DEFCOLOR_LABEL_TEXT				0xFFFFFFFF

// Button
#define DEFCOLOR_CCBUTTON_PLANE			DEFCOLOR_NORMAL
#define DEFCOLOR_CCBUTTON_LIGHTPLANE	DEFCOLOR_LIGHT
#define DEFCOLOR_CCBUTTON_DARKPLANE		DEFCOLOR_DARK
#define DEFCOLOR_CCBUTTON_TEXT			0xFF000000

// Edit
#define DEFCOLOR_CCEDIT_PLANE			DEFCOLOR_FRAME_PLANE
#define DEFCOLOR_CCEDIT_OUTLINE			DEFCOLOR_FRAME_OUTLINE
#define DEFCOLOR_CCEDIT_TEXT			0xFFCDCDCD

// List
#define DEFCOLOR_CCLIST_PLANE			0xFF141414
#define DEFCOLOR_CCLIST_OUTLINE			DEFCOLOR_FRAME_OUTLINE
#define DEFCOLOR_CCLIST_SELECTEDPLANE	DEFCOLOR_CCLIST_OUTLINE
#define DEFCOLOR_CCLIST_TEXT			0xFFCDCDCD
#define DEFCOLOR_CCLIST_SELECTEDTEXT	DEFCOLOR_CCLIST_PLANE

// ScollBar
#define DEFCOLOR_CCSCROLLBAR_PLANE		0xFF000000

// Popup
#define DEFCOLOR_CCPOPUP_PLANE			DEFCOLOR_FRAME_PLANE
#define DEFCOLOR_CCPOPUP_SELECTEDPLANE	DEFCOLOR_FRAME_OUTLINE
#define DEFCOLOR_CCPOPUP_TEXT			DEFCOLOR_FRAME_TEXT
#define DEFCOLOR_CCPOPUP_SELECTEDTEXT	DEFCOLOR_CCPOPUP_PLANE

// ToolTip
#define DEFCOLOR_CCTOOLTIP_PLANE		DEFCOLOR_FRAME_PLANE
#define DEFCOLOR_CCTOOLTIP_OUTLINE		DEFCOLOR_FRAME_OUTLINE
#define DEFCOLOR_CCTOOLTIP_TEXT			DEFCOLOR_FRAME_TEXT

// Frame
#define DEFCOLOR_CCFRAME_PLANE			DEFCOLOR_FRAME_PLANE
#define DEFCOLOR_CCFRAME_OUTLINE		DEFCOLOR_FRAME_OUTLINE
#define DEFCOLOR_CCMENUBAR_PLANE		DEFCOLOR_NORMAL
#define DEFCOLOR_CCMENUBAR_TEXT			0xFF000000

// Panel
#define DEFCOLOR_CCPANEL_PLANE			0x00000000
#define DEFCOLOR_CCPANEL_BORDER			DEFCOLOR_NORMAL